version: "3"
services:
  springapname:
    image: spring-boot-docker
    networks:
      - springapname-secondapname
    depends_on :
      - secondapname     
         
  secondapname:
    image: second-test  
    networks:
      - springapname-secondapname   
    ports:
      - "8080:8080"
networks:
  springapname-secondapname:
 